# Generated by Django 4.0.3 on 2022-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_note_contact_contact_note_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
