# Generated by Django 4.0.3 on 2022-06-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_note_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
